CREATE TABLE IF NOT EXISTS member (
MEMBER_SNO  INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
MEMBER_ID   VARCHAR(100) NOT NULL,
MEMBER_PWD  VARCHAR(255) NOT NULL,
MEMBER_NM   VARCHAR(100),
MEMBER_ROLE VARCHAR(50),
INS_DT      DATETIME,
UPD_DT      DATETIME,
ENABLE      CHAR(1)
);
-- 테스트 계정: ID=test / PW=1234
INSERT INTO member (MEMBER_ID, MEMBER_PWD, MEMBER_NM, MEMBER_ROLE, INS_DT, ENABLE)
VALUES ('test', '$2a$10$nHL59RoPxQfvH.MoSJ3nH.h14aBLpq.k85HCx0RUAiMj8ZXgPaJTW', '테스트유저', 'ROLE_MEMBER', NOW(), 'Y');